// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAz_ZB7zHrs9GEAm4Hv3FiZRZQUj0WAjI',
    appId: '1:327977533282:web:f22e3528a7ff53fd88363b',
    messagingSenderId: '327977533282',
    projectId: 'ebikeapp-2b5d7',
    authDomain: 'ebikeapp-2b5d7.firebaseapp.com',
    databaseURL: 'https://ebikeapp-2b5d7-default-rtdb.firebaseio.com',
    storageBucket: 'ebikeapp-2b5d7.appspot.com',
    measurementId: 'G-97JM2RJK8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXFb2jIJM_zuaEkKRt9KHX4I6pIOMaE8',
    appId: '1:327977533282:android:2e9f59ffed361b7788363b',
    messagingSenderId: '327977533282',
    projectId: 'ebikeapp-2b5d7',
    databaseURL: 'https://ebikeapp-2b5d7-default-rtdb.firebaseio.com',
    storageBucket: 'ebikeapp-2b5d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACokkeBHbZkie6P00gZnrKu1YFR3Hs0U4',
    appId: '1:327977533282:ios:1d7f5dc7082f2a1488363b',
    messagingSenderId: '327977533282',
    projectId: 'ebikeapp-2b5d7',
    databaseURL: 'https://ebikeapp-2b5d7-default-rtdb.firebaseio.com',
    storageBucket: 'ebikeapp-2b5d7.appspot.com',
    iosClientId: '327977533282-do1k7da7j5rhfbgabqpcbm9grs4aq1qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACokkeBHbZkie6P00gZnrKu1YFR3Hs0U4',
    appId: '1:327977533282:ios:db49be7f3af8d1fa88363b',
    messagingSenderId: '327977533282',
    projectId: 'ebikeapp-2b5d7',
    databaseURL: 'https://ebikeapp-2b5d7-default-rtdb.firebaseio.com',
    storageBucket: 'ebikeapp-2b5d7.appspot.com',
    iosClientId: '327977533282-gjcv5sfj8dfv3uk1158kui632n6dmvs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
